import { Movie } from "@/types/movie";

const cast = (names: string[]) =>
  names.map((name, i) => ({ id: i + 1, name, character: "", photo: null }));

export const MOCK_MOVIES: Movie[] = [
  {
    id: 1, imdb_code: "tt9362722",
    title: "Spider-Man: Across the Spider-Verse", czech_title: "Spider-Man: Napříč Spider-Versem",
    year: 2023, runtime: 140, genres: ["Animation", "Action"],
    overview: "Miles Morales se vydává na cestu přes Spider-Verse.",
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    ratings: { imdb: 8.6, tmdb: 8.4, rt: "95%", metacritic: "86/100" },
    cast: cast(["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"]),
    director: { id: 1, name: "Joaquim Dos Santos", photo: null },
    date_added: new Date().toISOString(), sources: ["yts", "srrdb"],
    torrents: [{ quality: "2160p", type: "BluRay", size: "12.5 GB", seeds: 2341 }],
  },
  {
    id: 2, imdb_code: "tt15398776",
    title: "Oppenheimer", czech_title: null,
    year: 2023, runtime: 180, genres: ["Biography", "Drama"],
    overview: "Příběh fyzika J. Roberta Oppenheimera a vývoje atomové bomby.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGl1.jpg",
    ratings: { imdb: 8.3, tmdb: 8.1, rt: "93%", metacritic: "88/100" },
    cast: cast(["Cillian Murphy", "Emily Blunt", "Matt Damon"]),
    director: { id: 525, name: "Christopher Nolan", photo: null },
    date_added: new Date().toISOString(), sources: ["yts"],
    torrents: [{ quality: "1080p", type: "BluRay", size: "8.2 GB", seeds: 5621 }],
  },
  {
    id: 3, imdb_code: "tt21692408",
    title: "Past Lives", czech_title: "Minulé životy",
    year: 2023, runtime: 106, genres: ["Drama", "Romance"],
    overview: "Dvě kamarádky z dětství se po dvaceti letech setkají v New Yorku.",
    poster: "https://image.tmdb.org/t/p/w500/k3waqVXSnYrMeiLZoHhWvMBHaFr.jpg",
    backdrop: null,
    ratings: { imdb: 7.9, tmdb: 7.8, rt: "98%", metacritic: "95/100" },
    cast: cast(["Greta Lee", "Teo Yoo", "John Magaro"]),
    director: { id: 2, name: "Celine Song", photo: null },
    date_added: new Date().toISOString(), sources: ["tmdb", "predb"],
    torrents: [{ quality: "1080p", type: "WEB-DL", size: "5.1 GB", seeds: 892 }],
  },
  {
    id: 4, imdb_code: "tt14230388",
    title: "Aftersun", czech_title: null,
    year: 2022, runtime: 101, genres: ["Drama"],
    overview: "Dospělá Sophie se ohlíží za dovolenou se svým otcem.",
    poster: "https://image.tmdb.org/t/p/w500/a3HpCMLM7PEVYTWoKDqVV9WMZv5.jpg",
    backdrop: null,
    ratings: { imdb: 7.6, tmdb: 7.5, rt: "96%", metacritic: "96/100" },
    cast: cast(["Paul Mescal", "Frankie Corio"]),
    director: { id: 3, name: "Charlotte Wells", photo: null },
    date_added: new Date().toISOString(), sources: ["tmdb"],
    torrents: [{ quality: "1080p", type: "BluRay", size: "6.3 GB", seeds: 441 }],
  },
  {
    id: 5, imdb_code: "tt1517268",
    title: "Barbie", czech_title: null,
    year: 2023, runtime: 114, genres: ["Comedy", "Fantasy"],
    overview: "Barbie a Ken se vydají z Barbieland do reálného světa.",
    poster: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIjx1RssCA4.jpg",
    ratings: { imdb: 6.9, tmdb: 7.1, rt: "88%", metacritic: "80/100" },
    cast: cast(["Margot Robbie", "Ryan Gosling", "America Ferrera"]),
    director: { id: 44716, name: "Greta Gerwig", photo: null },
    date_added: new Date().toISOString(), sources: ["yts", "scnsrc"],
    torrents: [
      { quality: "2160p", type: "BluRay", size: "15 GB", seeds: 4102 },
      { quality: "1080p", type: "BluRay", size: "7.2 GB", seeds: 8934 },
    ],
  },
];
