import { Movie } from "@/types/movie";

export const MOCK_MOVIES: Movie[] = [
  {
    id: 1,
    imdb_code: "tt9362722",
    title: "Spider-Man: Across the Spider-Verse",
    title_long: "Spider-Man: Across the Spider-Verse (2023)",
    czech_title: "Spider-Man: Napříč Spider-Versem",
    year: 2023,
    runtime: 140,
    genres: ["Animation", "Action", "Adventure"],
    overview:
      "Miles Morales se vydává na cestu přes Spider-Verse, kde se setkává s týmem Spider-Manů zodpovědných za ochranu jeho existence. Když hrdinové nesouhlasí s tím, jak zvládnout novou hrozbu, Miles se ocitá sám proti zbytku Spider-Society.",
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    ratings: { imdb: 8.6, tmdb: 8.4, rt: "95%", metacritic: "86/100" },
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    director: "Joaquim Dos Santos",
    date_uploaded: new Date().toISOString(),
    scene_confirmed: true,
    torrents: [{ quality: "2160p", type: "BluRay", size: "12.5 GB", seeds: 2341 }],
  },
  {
    id: 2,
    imdb_code: "tt15398776",
    title: "Oppenheimer",
    title_long: "Oppenheimer (2023)",
    czech_title: "Oppenheimer",
    year: 2023,
    runtime: 180,
    genres: ["Biography", "Drama", "History"],
    overview:
      "Příběh amerického fyzika J. Roberta Oppenheimera a jeho role při vývoji atomové bomby během druhé světové války. Dramatický pohled na muže, který změnil svět.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGl1.jpg",
    ratings: { imdb: 8.3, tmdb: 8.1, rt: "93%", metacritic: "88/100" },
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    director: "Christopher Nolan",
    date_uploaded: new Date().toISOString(),
    scene_confirmed: false,
    torrents: [
      { quality: "1080p", type: "BluRay", size: "8.2 GB", seeds: 5621 },
      { quality: "720p", type: "BluRay", size: "4.1 GB", seeds: 3102 },
    ],
  },
  {
    id: 3,
    imdb_code: "tt21692408",
    title: "Past Lives",
    title_long: "Past Lives (2023)",
    czech_title: "Minulé životy",
    year: 2023,
    runtime: 106,
    genres: ["Drama", "Romance"],
    overview:
      "Dvě kamarádky z dětství z Koreje se po dvaceti letech setkají v New Yorku a řeší, co pro ně znamená láska, osud a pouto, které nikdy nepřerušily.",
    poster: "https://image.tmdb.org/t/p/w500/k3waqVXSnYrMeiLZoHhWvMBHaFr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/kEROHFEwdlxRHiOb3rAJbD5OREA.jpg",
    ratings: { imdb: 7.9, tmdb: 7.8, rt: "98%", metacritic: "95/100" },
    cast: ["Greta Lee", "Teo Yoo", "John Magaro"],
    director: "Celine Song",
    date_uploaded: new Date().toISOString(),
    scene_confirmed: false,
    torrents: [{ quality: "1080p", type: "WEB-DL", size: "5.1 GB", seeds: 892 }],
  },
  {
    id: 4,
    imdb_code: "tt14230388",
    title: "Aftersun",
    title_long: "Aftersun (2022)",
    czech_title: "Aftersun",
    year: 2022,
    runtime: 101,
    genres: ["Drama"],
    overview:
      "Dospělá Sophie se ohlíží za dovolenou, kterou strávila se svým otcem Callumem před dvaceti lety. Rekonstruuje vzpomínky a uvědomuje si, co tehdy nedokázala vidět.",
    poster: "https://image.tmdb.org/t/p/w500/a3HpCMLM7PEVYTWoKDqVV9WMZv5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mwl8aN8TmgSj8GXLPM78LpvHlU0.jpg",
    ratings: { imdb: 7.6, tmdb: 7.5, rt: "96%", metacritic: "96/100" },
    cast: ["Paul Mescal", "Frankie Corio"],
    director: "Charlotte Wells",
    date_uploaded: new Date().toISOString(),
    scene_confirmed: false,
    torrents: [{ quality: "1080p", type: "BluRay", size: "6.3 GB", seeds: 441 }],
  },
  {
    id: 5,
    imdb_code: "tt17351924",
    title: "Rye Lane",
    title_long: "Rye Lane (2023)",
    czech_title: "Rye Lane",
    year: 2023,
    runtime: 82,
    genres: ["Comedy", "Romance"],
    overview:
      "Dva mladí Londýňané, kteří si prochází bolestivým rozchodem, se náhodně setkají a stráví spolu jeden den plný upřímnosti a humoru.",
    poster: "https://image.tmdb.org/t/p/w500/nMGxYBJomTANOXpT4WZIyvWDdZ5.jpg",
    backdrop: null,
    ratings: { imdb: 7.1, tmdb: 7.2, rt: "100%", metacritic: null },
    cast: ["Vivian Oparah", "David Jonsson"],
    director: "Raine Allen-Miller",
    date_uploaded: new Date().toISOString(),
    scene_confirmed: false,
    torrents: [{ quality: "1080p", type: "WEB-DL", size: "3.8 GB", seeds: 203 }],
  },
  {
    id: 6,
    imdb_code: "tt1517268",
    title: "Barbie",
    title_long: "Barbie (2023)",
    czech_title: "Barbie",
    year: 2023,
    runtime: 114,
    genres: ["Adventure", "Comedy", "Fantasy"],
    overview:
      "Barbie a Ken se vydají z Barbieland do reálného světa, kde Barbie zjistí, že být ženou je složitější, než si myslela.",
    poster: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIjx1RssCA4.jpg",
    ratings: { imdb: 6.9, tmdb: 7.1, rt: "88%", metacritic: "80/100" },
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera"],
    director: "Greta Gerwig",
    date_uploaded: new Date().toISOString(),
    scene_confirmed: true,
    torrents: [
      { quality: "2160p", type: "BluRay", size: "15 GB", seeds: 4102 },
      { quality: "1080p", type: "BluRay", size: "7.2 GB", seeds: 8934 },
    ],
  },
];
